### ISSUE TITLE
Only annotation mapping is supported by make:entity

### ISSUE THREAD

**Issue by imajim** [Sylius/SyliusResourceBundle#147]
**Sylius version affected**: 1.6.5 sylius/sylius-standard

When i execute this command : 
 `php bin/console make:entity --no-debug`
or
` php bin/console make:entity`

i've got this error:
```
Class name of the entity to create or update (e.g. VictoriousJellybean):
 > test

 created: src/Entity/Test.php
 created: src/Repository/TestRepository.php

                                                                                                                        
 [ERROR] Only annotation mapping is supported by make:entity, but the <info>App\Entity\Test</info> class uses a         
         different format. If you would like this command to generate the properties & getter/setter methods, add your  
         mapping configuration, and then re-run this command with the <info>--regenerate</info> flag. 
```

I fix with my hack : https://github.com/Sylius/SyliusResourceBundle/issues/103
but it's not working now... :(

**Comment by j0r1s** [comment]
I'm encoutering the same problem after upgrading from `sylius/resource-bundle:1.5 -> 1.6`

**Comment by imajim** [comment]
For information i've tested on local (Mac os X + MAMP) and on dedicated server (webserver linux...)

**Comment by j0r1s** [comment]
Hey @imajim, I've fixed it using this patch https://github.com/vklux/maker-bundle-force-annotation

**Comment by imajim** [comment]
@j0r1s Yep i saw it and it's working 👍

**Comment by okhachiai** [comment]
It's a bug in the doctrine version please try this version good luck

    composer req doctrine/doctrine-bundle:2.2

**Comment by Thaldos** [comment]
> It's a bug in the doctrine version please try this version good luck
> 
> ```
> composer req doctrine/doctrine-bundle:2.2
> ```

Works perfectly on Symfony 5.2.5, thanks.

**Comment by endelwar** [comment]
This bug is fixed in symfony/maker-bundle 1.30.1

**Comment by Thaldos** [comment]
> This bug is fixed in symfony/maker-bundle 1.30.1

I confirm. Thx :) !

I upgrade `symfony/maker-bundle 1.30.0` to  `symfony/maker-bundle 1.30.1` with the command `composer update --dev` and it works too.

**Comment by aliemre** [comment]
It is fixed on `symfony/maker-bundle 1.30.1` . Confirmed!

**Comment by Saerdn** [comment]
Looks like the bug is back on the menu with  symfony/maker-bundle v1.38 :(

**Comment by refatalsakka** [comment]
> Solved: The entity dir was not correctly mapped in the doctrine.yaml file (the structure slightly changed to older versions). Now its working.

Can you please show me, how exactly did you fix it.

**Comment by HAMDIAmenAllah** [comment]
It was fixed on symfony/maker-bundle 1.30.1 . Confirmed!
